#!/usr/bin/env python

"""
    Setup script for OpenRadiac calculations.
  
   
    Written by Carlos A. Gimenez, Natural and Exact Science Faculty
                                  Northeastern University of Argentina,
        			  Corrientes, Argentina
   
    Contributors: --
   
    Environment variables used by pam:
             DIRTIMEOUT        - time out limit for OpenRadiac run
          
"""

import os
import sys

if sys.version < '2.4':
    print('pam requires python version >= 2.4')
    sys.exit(1)

class set_enviroment:
  """
  class for handling the OpenRadiac run
  """
  def __init__(self):
    """
    Initialize the global set of variables
    """
  def main_run(self):
    src = os.getcwd() 
    os.system("cmake -P distclean.cmake")
    print "runing cmake clean"
    os.system("make distclean")
    print "done"

set_enviroment().main_run()

print "The AMCalc was cleaned"
