#!/usr/bin/env python

"""
    Save changes script for OpenRadiac calculations.
  
   
    Written by Carlos A. Gimenez, Natural and Exact Science Faculty
                                  Northeastern University of Argentina,
        			  Corrientes, Argentina
   
    Contributors: Francisco Passian
   
    Environment variables used by pam:
             DIRTIMEOUT        - time out limit for OpenRadiac run
          
"""

import os
import sys

if sys.version < '2.4':
    print('pam requires python version >= 2.4')
    sys.exit(1)

class set_enviroment:
  """
  class for handling the OpenRadiac run
  """
  def __init__(self):
    """
    Initialize the global set of variables
    """
  def main_run(self):
#    src = os.getcwd() 
    print 'save changes'
    os.system("git add *")
    print '-----------------------------------'
    print 'write a nice message for reference'
    print 'including quotes'
    print 'Example "Change function Klein-Nishina"'
    print '-----------------------------------'
    msg = raw_input('--->')
    os.system("echo"+msg)
    print "done"
    os.system("git commit -a -m"+msg)
set_enviroment().main_run()

print '-----------------------------------'
print '    Thanks!, enjoy your meal       '
print '-----------------------------------'
