#!/usr/bin/env python

"""
    Launch script for amcalc calculations.
  
   
    Written by Carlos A. Gimenez, Natural and Exact Science Faculty
                                  Northeastern University of Argentina,
        		 	  Corrientes, Argentina
   
    Contributors: --
   
    Environment variables used by pam:
             DIRTIMEOUT        - time out limit for amcalc run
          
"""

import os
import sys

if sys.version < '2.4':
    print('pam requires python version >= 2.4')
    sys.exit(1)

class set_enviroment:
  """
  class for handling the amcalc run
  """
  def __init__(self):
    """
    Initialize the global set of variables
    """
  def main_run(self):
    os.system("./amcalc")


set_enviroment().main_run()
