#!/usr/bin/env python

"""
    Launch script for amcalc calculations.
  
   
    Written by Carlos A. Gimenez, Natural and Exact Science Faculty
                               Northeastern University of Argentina,
        			Corrientes, Argentina
   
    Contributors: --
   
    Environment variables used by pam:
             DIRTIMEOUT        - time out limit for amcalc run
          
"""

import os
import sys

if sys.version < '2.4':
    print('pam requires python version >= 2.4')
    sys.exit(1)

class set_enviroment:
  """
  class for handling the amcalc run
  """
  def __init__(self):
    """
    Initialize the global set of variables
    """
  def main_run(self):
    os.system("gfortran amcalc.f90 ")
    os.system("./a.out")

#    for files in source:
#      if files.endswith(".dat"):
#        shutil.copy(src+files,destination)

#  def clean_environment(self):
#    for rm_files in glob.glob('*.dat'):
#      os.remove(rm_files)


set_enviroment().main_run()
