#!/usr/bin/env python

"""
    Launch script for amcalc test.
  
   
    Written by Carlos A. Gimenez, Natural and Exact Science Faculty
                               Northeastern University of Argentina,
        			Corrientes, Argentina
   
    Contributors: --
   
    Environment variables used by pam:
             DIRTIMEOUT        - time out limit for amcalc run
          
"""

import os
import sys
import shutil
import glob
import subprocess

if sys.version < '2.4':
    print('pam requires python version >= 2.4')
    sys.exit(1)

class set_environment:
  """
  class for handling the amcalc run
  """
  def __init__(self):
    """
    Initialize the global set of variables
    """
#  def main_run(self):
#   os.system("gfortran amcalc.f90 -o binamcalc")
#   os.system("./amcalc")

  def prepare_files(self):
    src = os.getcwd()+"/example/"
    test_folder = os.getcwd()+"/test/"

    if not os.path.exists(test_folder):
      os.makedirs(test_folder)

    source = os.listdir(src)

    for files in source:
      if files.endswith(".dat"):
        shutil.copy(src+files,test_folder)
    
    shutil.copy(os.getcwd()+"/bin/amcalc",test_folder)
     
    p = subprocess.Popen(["./amcalc"], cwd=test_folder)
    p.wait()
# Run code in different folder

#  def clean_environment(self):
#    for rm_files in glob.glob('*.dat'):
#      os.remove(rm_files)

#  def grafic(self):
#    os.system("gnuplot atenuacion.gnu")
#    os.system("gnuplot histograma.gnu")
#    os.system("gnuplot seccion.gnu")
#    os.system("gnuplot seccion_log.gnu")

set_environment().prepare_files()
#set_environment().main_run()
print "Generando graficos"
#set_environment().grafic()
print "clean enviroment"
#set_environment().clean_environment()
